[package]
name = "vakthund"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "vakthund"
path = "src/main.rs"


[workspace]
members = [
    "crates/vakthund-common",
    "crates/vakthund-capture",
    "crates/vakthund-protocol",
    "crates/vakthund-detection",
    "crates/vakthund-monitor",
    "crates/vakthund-core",
    "crates/vakthund-simulation"
]

[dependencies]
vakthund-common = { path = "crates/vakthund-common" }
vakthund-core   = { path = "crates/vakthund-core" }

[dev-dependencies.cargo-husky]
version = "1"
default-features = false
features = ["user-hooks"]
