capture:
  buffer_size: 4096
  promiscuous: true
  flush_interval: 1s

detection:
  rules:
    - "alert tcp any any -> any 80 (msg:\"HTTP Request detected\"; sid:1001;)"
    - "alert udp any any -> any 53 (msg:\"DNS Request detected\"; sid:1002;)"
  thresholds:
    max_alerts_per_second: 1000

simulation:
  segment_size: 134217728  # 128 MB
  time_scale: 1s

reporting:
  snapshots:
    directory: "snapshots"
    retention: 3600s
  alerts:
    console: true
    syslog:
      server: "localhost"
      port: 514

