[package]
name = "vakthund-detection"
version = "0.1.0"
edition = "2021"
description = "Detection engine for Vakthund that analyzes parsed packets"
license = "MIT"

[dependencies]
vakthund-protocol = { path = "../vakthund-protocol" }
vakthund-common = { path = "../vakthund-common" }
