[package]
name = "vakthund-core"
version = "0.1.0"
edition = "2021"

[dependencies]
bytes = { workspace = true }
crossbeam = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
proptest = { workspace = true }
bumpalo = "3.17.0"
rand = { version = "0.9.0", features = ["small_rng", "std"] }
concurrent-queue = "2.5.0"

[dev-dependencies]
criterion = "0.5.1"

[[bench]]
name = "event_bus_bench"
harness = false
