[package]
name = "vakthund-monitor"
version = "0.1.0"
edition = "2021"
description = "Traffic monitor for Vakthund IDPS that applies quarantines and thresholds"
license = "MIT"

[dependencies]
vakthund-common = { path = "../vakthund-common" }
