#!/bin/sh

set -e

echo '+cargo test --all'
cargo test --all

echo '+cargo audit'
# TODO: (#RUSTSEC-2024-0437): Currently using 'protobuf' 2.28.0 with known recursion vulnerability
# No fixed release available. Remove this ignore when patched version exists
cargo audit --ignore RUSTSEC-2024-0437
