[package]
name = "vakthund-capture"
version = "0.1.0"
edition = "2021"

# Proprietary and confidential. All rights reserved.

[dependencies]
vakthund-common = { path = "../vakthund-common" }
ctrlc = "3"
rand = "0.8"
sha2 = "0.10"
hex = "0.4"
chrono = "0.4.39"
tracing = "0.1.41"
